### PR TITLE
Fix ansible-doc typo

### PR DESCRIPTION
**Pull request by alagoutte**
Fix typo found when use ansible-doc

### CODE REVIEW

**Comment by tchiapuziowong** [comment]
Hi @alagoutte !  Thank you so much for this contribution!! - Please sign off the DCO by adding a "signed off" message to your commit - see here: https://github.com/aruba/aos-switch-ansible-collection/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by alagoutte** [comment]
> Hi @alagoutte ! Thank you so much for this contribution!! - Please sign off the DCO by adding a "signed off" message to your commit - see here: https://github.com/aruba/aos-switch-ansible-collection/blob/master/CONTRIBUTING.md#sign-your-work

it is good !

**Comment by gundalow** [comment]
Looks like `ansible-test sanity` isn't running on this repo, which would have helped with some of these.
If you copy https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml (updating lines 20 & 21), you'll get that enabled.

Feel free to ping me on the PR if you have any issues

**Comment by alagoutte** [comment]
> Looks like `ansible-test sanity` isn't running on this repo, which would have helped with some of these. If you copy https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml (updating lines 20 & 21), you'll get that enabled.
> 
> Feel free to ping me on the PR if you have any issues

Oh Yes, good idea... (also on aocx-ansible-collection too)

can be nice also to add some CI test for publish new release...

**Pull request merged**
